### PR TITLE
#163382819 Implement design feedbacks on UI templates

### PR DESCRIPTION
**Pull request by haywhyze**
#### What does this PR do?
This PR implements design feedbacks on UI templates

#### Description of Task to be completed?
- Use more contrasting colors on cards
- Make background image on profile page less prominent
- Change the background color of the table cells on the my-vote tab on the profile page
- The modal close button should be moved inside the modal for clarity
- Highlight the tab-link that is active
- make mobile-menu list centered and differentiate from site logo

- use a dark overlay for the form and table on the profile page
- change color of the second header on the profile page
- change cards color to blue on the voting page.

#### How should this be manually tested?
- Clone this repository 
- Checkout branch `ch-implement-feedback-ui-163382819`  
- cd into UI folder and open index.html with any modern browser

#### What are the relevant pivotal tracker stories?
[#163382819](https://www.pivotaltracker.com/story/show/163382819)

#### Screenshots
- Use more contrasting colors on cards
Before
politico-color-contrast-before

After
politico-color-contrast-after

- Make background image on profile page less prominent
Before
politico-bgcolor-less-prominent-before

After
politico-bgcolor-less-prominent-after

- Change the background color of the table cells on the my-vote tab on the profile page
Before
politico-table-color-before

After
politico-table-color-after

- The modal close button should be moved inside the modal for clarity
Before
politico-modal-close-before

After
politico-modal-close-after

- Highlight the tab-link that is active
Before
politico-highlight-active-before

After
politico-highlight-active-after

- make mobile-menu list centered and differentiate from site logo
Before
politico-mobile-menu-before

After
politico-mobile-menu-after

- use a dark overlay for the form and table on the profile page and change color of the second header
politico-dark-overlay3
politico-dark-overlay2
politico-dark-overlay

- change cards color to blue on the voting page.
politico-change-cards-to-blue

change the cards of the modal back to the blue color with the white text.
politico-new2

- adopt a dark background and change the color of the cards to white
politico-new

### CODE REVIEW

**Comment by megame24** [comment]
Please include screenshots

**Comment by megame24** [comment]
Since this task has to do with updating the UI that impacts the users, do you think a `chore` story is the appropriate type for this task?

**Comment by haywhyze** [comment]
> Please include screenshots

Okay, I will now.

**Comment by haywhyze** [comment]
> Since this task has to do with updating the UI that impacts the users, do you think a `chore` story is the appropriate type for this task?

It should have been a feature. Should I effect the changes on pt board and create another branch for it or just the changes on pt board?

**Comment by megame24** [comment]
> > Since this task has to do with updating the UI that impacts the users, do you think a `chore` story is the appropriate type for this task?
> 
> It should have been a feature. Should I effect the changes on pt board and create another branch for it or just the changes on pt board?

You can just change it on PT, but going forward, take note of that.

**Comment by megame24** [comment]
For the second and third set of screenshots, let's use a dark overlay, instead of a light one, and also change the color of the second header(the red text). Using a dark overlay will highlight the form and the table which have a primary color of white

**Comment by megame24** [comment]
For the voting page, let's maintain the color blue for the cards instead of white, this will ensure they stand out since the background is already white.

**Comment by haywhyze** [comment]
> > > Since this task has to do with updating the UI that impacts the users, do you think a `chore` story is the appropriate type for this task?
> > 
> > 
> > It should have been a feature. Should I effect the changes on pt board and create another branch for it or just the changes on pt board?
> 
> You can just change it on PT, but going forward, take note of that.

Okay.

**Comment by megame24** [comment]
Good job on implementing most of the feedback, but by the voting page I meant the page that had `Buhari` and `Atiku`, change the cards back to the blue color with the white text.
For the screenshot with the heading `change cards color to blue on the voting page.`, I suggest you adopt the new dark background and change the color of the cards to white instead of the blue background with red headings that is there now.

**Comment by haywhyze** [comment]
> Good job on implementing most of the feedback, but by the voting page I meant the page that had `Buhari` and `Atiku`, change the cards back to the blue color with the white text.
> For the screenshot with the heading `change cards color to blue on the voting page.`, I suggest you adopt the new dark background and change the color of the cards to white instead of the blue background with red headings that is there now.

- I had done the modal changes but didn't include it in the screenshots. Now added.
- Now adopted the dark backround.

**Review by megame24 — APPROVED** [review]
Looks good, nice job. You can merge.

**Pull request merged**
