### PR TITLE
#163423678 Edit party name

### PR DESCRIPTION
**Pull request by haywhyze**
#### What does this PR do?
Implements update party name via `/parties/<party-id>/name`
#### Description of Task to be completed?
- write test scripts to test the update party name functionality
- create patchName method to handle patch request to `/parties/<party-id>/name`
- add the patchName method and the necessary middlewares to the router

#### How should this be manually tested?
- clone this repository by executing `git clone https://github.com/haywhyze/politico.git`
- cd to the cloned local repository `cd politico`
- run `git checkout ft-edit-party-name-163423678`
- install all dependencies by running `npm install`
- start the server with `npm start`
- when the server is up, you can test using Postman or any other related service.

#### What are the relevant pivotal tracker stories?
[#163423678](https://www.pivotaltracker.com/story/show/163423678)

### CODE REVIEW

**Review by akinwale-habibullah — APPROVED** [review]
Good job. 

A piece of feedback;

Add the details of variables that need to be added in the .env file in your README file.

**Comment by akinwale-habibullah** [comment]
Also why are using require('cloudinary'). Please use import construct in all files rather than mix require and import.

**Comment by akinwale-habibullah** [comment]
Get rid of inline style rules rather use rules in .eslintrc

**Comment by haywhyze** [comment]
@akinwale-habibullah I have effected the changes you suggested

**Review by akinwale-habibullah — APPROVED** [review]

**Pull request merged**
